[package]
name = "ech-db-integration-tests"
version.workspace = true
edition.workspace = true

[dependencies]
ech-db-protocol = { path = "../../crates/ech-db-protocol" }
ech-db-server = { path = "../../crates/ech-db-server" }
ech-db-client = { path = "../../crates/ech-db-client" }
ech-db-recovery = { path = "../../crates/ech-db-recovery" }
ech-db-test-fixtures = { path = "../fixtures" }
foundationdb-tuple.workspace = true
tonic.workspace = true
tokio.workspace = true
bcs.workspace = true
serde.workspace = true
rand.workspace = true
ed25519-dalek.workspace = true
wasmi.workspace = true
wat.workspace = true
